name: bike router ci
on:
  push:
    branches: [master]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: build
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: run tests
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test # will run `yarn test` command
